name: CI
permissions:
  contents: write  # Cho phép token có quyền ghi vào repository
on:
  push:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.12'

      - name: Install pnpm
        run: npm i -g pnpm

      - name: Check if last commit contains 'build_cot_cache'
        id: check-commit
        run: |
          if git log -1 --pretty=%B | grep -q 'build_cot_cache'; then
          echo "SKIP_CACHE=true" >> $GITHUB_ENV
          else
          echo "SKIP_CACHE=false" >> $GITHUB_ENV
          fi

      - name: Cache Node.js modules
        if: env.SKIP_CACHE == 'false'
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install deps
        run: pnpm install
      - name: Push code to main
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "thanhlv@thanhlv.com"
      - name: Build
        run: npm run build_github
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages