name: Wait for Deploy

on:
  workflow_run:
    workflows:
      - pages-build-deployment
    types:
      - completed

jobs:
  test-job:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Send Telegram Message
        uses: cbrgm/telegram-github-action@v1
        with:
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          to: ${{ vars.TELEGRAM_CHAT_ID }}
          thread-id: ${{ vars.MESSAGE_THREAD_ID_DEPLOY_THANHLV_BLOG }}
          message: "Build thanhlv.com with build number: ${{github.run_number}}, 🚀 Deploy to thanhlv.com completed successfully!"